const alldata = [
  {
    id: 1,
    brand: "Chanel",
    name: "Chanel No. 5",
    company: "Chanel",
    price: "$135",
    discount_price: "$120",
    discount: true,
    size: "100ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Chanel_No._5_Fragrance_Austin_Calhoon_Photograph.jpg",
    origin_country: "France",
  },
  {
    id: 2,
    brand: "Dior",
    name: "Miss Dior",
    company: "Christian Dior",
    price: "$145",
    discount: false,
    size: "100ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://i5.walmartimages.com/asr/c3aa5a92-8fae-4d83-aa76-f02ed5b0d966_1.be808ab66d532816b708ba88fd163919.jpeg",
    origin_country: "France",
  },
  {
    id: 3,
    brand: "Gucci",
    name: "Gucci Bloom",
    company: "Gucci",
    price: "$120",
    discount_price: "$100",
    discount: true,
    size: "100ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://thedecantcompany.com/wp-content/uploads/2023/08/375x500.79602.jpg",
    origin_country: "Italy",
  },
  {
    id: 4,
    brand: "Tom Ford",
    name: "Black Orchid",
    company: "Tom Ford",
    price: "$180",
    discount: false,
    size: "100ml",
    fragrance_type: "Oriental",
    gender: "Unisex",
    image:
      "https://buyperfumeinbangladesh.com/wp-content/uploads/2017/02/Tom-Ford-Black-Orchid-EDP-for-Men-and-Women-100ml.png",
    origin_country: "USA",
  },
  {
    id: 5,
    brand: "Yves Saint Laurent",
    name: "Libre",
    company: "Yves Saint Laurent",
    price: "$132",
    discount_price: "$115",
    discount: true,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Female",
    image:
      "https://www.gazzaz.com.sa/cdn/shop/products/100203012050_800x.jpg?v=1671527525",
    origin_country: "France",
  },
  {
    id: 6,
    brand: "Versace",
    name: "Bright Crystal",
    company: "Versace",
    price: "$105",
    discount: false,
    size: "90ml",
    fragrance_type: "Fruity",
    gender: "Female",
    image:
      "https://i0.wp.com/perfumeshop.com.bd/wp-content/uploads/2022/09/images-17_17.jpeg",
    origin_country: "Italy",
  },
  {
    id: 7,
    brand: "Burberry",
    name: "My Burberry",
    company: "Burberry",
    price: "$125",
    discount_price: "$110",
    discount: true,
    size: "90ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://m.media-amazon.com/images/I/91VjMRyO1kL._AC_UF350,350_QL80_.jpg",
    origin_country: "UK",
  },
  {
    id: 8,
    brand: "Armani",
    name: "Si",
    company: "Giorgio Armani",
    price: "$130",
    discount: false,
    size: "100ml",
    fragrance_type: "Chypre",
    gender: "Female",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8UdiAt20VFYHOCLDV_xlus8ZMrgZXI1Ou2Q&s",
    origin_country: "Italy",
  },
  {
    id: 9,
    brand: "Prada",
    name: "La Femme",
    company: "Prada",
    price: "$145",
    discount_price: "$130",
    discount: true,
    size: "100ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://m.media-amazon.com/images/I/615m4acTEMS._AC_UF1000,1000_QL80_.jpg",
    origin_country: "Italy",
  },
  {
    id: 10,
    brand: "Hermès",
    name: "Twilly d'Hermès",
    company: "Hermès",
    price: "$130",
    discount: false,
    size: "85ml",
    fragrance_type: "Spicy",
    gender: "Female",
    image:
      "https://www.scentstore.com/wp-content/uploads/2023/10/Hermes-Tutti-Twilly-85ml-Box.jpg",
    origin_country: "France",
  },
  {
    id: 11,
    brand: "Chanel",
    name: "Coco Mademoiselle",
    company: "Chanel",
    price: "$150",
    discount_price: "$135",
    discount: true,
    size: "100ml",
    fragrance_type: "Citrus",
    gender: "Female",
    image:
      "https://du0l56ab6b371.cloudfront.net/images/thumbs/0001760_chanel-coco-mademoiselle-edp_1000.webp",
    origin_country: "France",
  },
  {
    id: 12,
    brand: "Dior",
    name: "J'adore",
    company: "Christian Dior",
    price: "$142",
    discount: false,
    size: "100ml",
    fragrance_type: "Floral",
    gender: "Female",
    image:
      "https://du0l56ab6b371.cloudfront.net/images/thumbs/0001748_dior-jadore-edp_625.webp",
    origin_country: "France",
  },
  {
    id: 13,
    brand: "Gucci",
    name: "Gucci Guilty",
    company: "Gucci",
    price: "$125",
    discount: false,
    size: "100ml",
    fragrance_type: "Amber",
    gender: "Female",
    image:
      "https://shopatshams.com.pk/cdn/shop/files/730870179710_5ca40034-c8d1-42f8-bddf-e9977ca8a102_720x.jpg?v=1701147380",
    origin_country: "Italy",
  },
  {
    id: 14,
    brand: "Tom Ford",
    name: "Tobacco Vanille",
    company: "Tom Ford",
    price: "$210",
    discount_price: "$195",
    discount: true,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Unisex",
    image:
      "https://www.luxeoscent.in/cdn/shop/files/TomfordTobaccoVanille.webp?v=1722673269",
    origin_country: "USA",
  },
  {
    id: 15,
    brand: "Yves Saint Laurent",
    name: "Mon Paris",
    company: "Yves Saint Laurent",
    price: "$130",
    discount: false,
    size: "90ml",
    fragrance_type: "Fruity",
    gender: "Female",
    image:
      "https://swish.qa/cdn/shop/products/yslmonparisedp90ml_800x.jpg?v=1650619172",
    origin_country: "France",
  },
  {
    id: 16,
    brand: "Versace",
    name: "Dylan Blue",
    company: "Versace",
    price: "$120",
    discount_price: "$105",
    discount: true,
    size: "100ml",
    fragrance_type: "Aromatic",
    gender: "Male",
    image:
      "https://i0.wp.com/perfumeshop.com.bd/wp-content/uploads/2021/09/0001-7262092136_20210906_012545_0000.jpg?fit=1180%2C1180&ssl=1",
    origin_country: "Italy",
  },
  {
    id: 17,
    brand: "Burberry",
    name: "Brit Rhythm",
    company: "Burberry",
    price: "$110",
    discount: false,
    size: "90ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1vdnWSZubAAXTPHAYNRnRXMJkAqFoYzgcZg&s",
    origin_country: "UK",
  },
  {
    id: 18,
    brand: "Armani",
    name: "Aqua di Gio",
    company: "Giorgio Armani",
    price: "$130",
    discount: false,
    size: "100ml",
    fragrance_type: "Aromatic",
    gender: "Male",
    image: "https://dutyfree.b-cdn.net/423_0938_5a458d21ae.png",
    origin_country: "Italy",
  },
  {
    id: 19,
    brand: "Prada",
    name: "Luna Rossa",
    company: "Prada",
    price: "$125",
    discount_price: "$110",
    discount: true,
    size: "100ml",
    fragrance_type: "Citrus",
    gender: "Male",
    image:
      "https://www.fluxurymagazine.com/wp-content/uploads/2023/06/abertura-Prada-luna-rossa.jpg",
    origin_country: "Italy",
  },
  {
    id: 20,
    brand: "Hermès",
    name: "Voyage d'Hermès",
    company: "Hermès",
    price: "$140",
    discount: false,
    size: "100ml",
    fragrance_type: "Fresh",
    gender: "Unisex",
    image:
      "https://assets.hermes.com/is/image/hermesproduct/voyage-d-hermes-parfum--107569V0-worn-3-0-0-800-800_g.jpg",
    origin_country: "France",
  },
  {
    id: 21,
    brand: "Chanel",
    name: "Allure Homme Sport",
    company: "Chanel",
    price: "$150",
    discount_price: "$135",
    discount: true,
    size: "100ml",
    fragrance_type: "Citrus",
    gender: "Male",
    image:
      "https://fragrancebd.com/wp-content/uploads/2018/11/Chanel-Allure-Homme-Sport-Eau-Extreme-EDP-100mL-1.jpg",
    origin_country: "France",
  },
  {
    id: 22,
    brand: "Dior",
    name: "Sauvage",
    company: "Christian Dior",
    price: "$140",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWGXgPOFc32eiC3AZnxunAjwcdLhK28RshsQ&s",
    origin_country: "France",
  },
  {
    id: 23,
    brand: "Gucci",
    name: "Mémoire d'une Odeur",
    company: "Gucci",
    price: "$135",
    discount: false,
    size: "100ml",
    fragrance_type: "Herbal",
    gender: "Unisex",
    image:
      "https://m.media-amazon.com/images/I/615tDSzwcgL._AC_UF1000,1000_QL80_.jpg",
    origin_country: "Italy",
  },
  {
    id: 24,
    brand: "Tom Ford",
    name: "Neroli Portofino",
    company: "Tom Ford",
    price: "$230",
    discount_price: "$210",
    discount: true,
    size: "100ml",
    fragrance_type: "Citrus",
    gender: "Unisex",
    image:
      "https://sdcdn.io/tf/tf_sku_TCXM01_2000x2000_1.png?height=700px&options=BackgroundColor%3DF2F2F2&width=700px",
    origin_country: "USA",
  },
  {
    id: 25,
    brand: "Yves Saint Laurent",
    name: "Opium",
    company: "Yves Saint Laurent",
    price: "$125",
    discount: false,
    size: "90ml",
    fragrance_type: "Spicy",
    gender: "Female",
    image:
      "https://fragrancebd.com/wp-content/uploads/2020/03/YSL-Black-Opium-Intense-EDP-90mL.jpg",
    origin_country: "France",
  },
  {
    id: 26,
    brand: "Versace",
    name: "Eros",
    company: "Versace",
    price: "$130",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgbxC87jmZFdYOYevU-GqsYQzY6QzR0n8PLQ&s",
    origin_country: "Italy",
  },
  {
    id: 27,
    brand: "Burberry",
    name: "Brit",
    company: "Burberry",
    price: "$110",
    discount_price: "$95",
    discount: true,
    size: "100ml",
    fragrance_type: "Gourmand",
    gender: "Female",
    image:
      "https://buyperfumeinbangladesh.com/wp-content/uploads/2019/12/Burberry_Brit-Rhythm-for-Men-300x300.jpg",
    origin_country: "UK",
  },
  {
    id: 28,
    brand: "Armani",
    name: "Code",
    company: "Giorgio Armani",
    price: "$135",
    discount_price: "$120",
    discount: true,
    size: "100ml",
    fragrance_type: "Oriental",
    gender: "Male",
    image:
      "https://codegrooming.com/cdn/shop/files/Acqua_8a153410-5428-4f6d-b2e7-0bcfee055bca.png?v=1713258391",
    origin_country: "Italy",
  },
  {
    id: 29,
    brand: "Prada",
    name: "L'Homme",
    company: "Prada",
    price: "$145",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://media.takealot.com/covers_images/b3283b48d43a4c5d92dc2d6cd9b3bca3/s-pdpxl.file",
    origin_country: "Italy",
  },
  {
    id: 30,
    brand: "Hermès",
    name: "Terre d'Hermès",
    company: "Hermès",
    price: "$135",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp5dPyRl-0I7jhI65obVZeogy2ijzAq0YkwQ&s",
    origin_country: "France",
  },
  {
    id: 31,
    brand: "Chanel",
    name: "Bleu de Chanel",
    company: "Chanel",
    price: "$150",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image: "https://redolencenpl.com/wp-content/uploads/2024/04/4-2.jpg",
    origin_country: "France",
  },
  {
    id: 32,
    brand: "Dior",
    name: "Fahrenheit",
    company: "Christian Dior",
    price: "$140",
    discount_price: "$125",
    discount: true,
    size: "100ml",
    fragrance_type: "Leather",
    gender: "Male",
    image:
      "https://i0.wp.com/perfumeshop.com.bd/wp-content/uploads/2022/03/1228.jpg?fit=554%2C554&ssl=1",
    origin_country: "France",
  },
  {
    id: 33,
    brand: "Gucci",
    name: "Gucci Oud",
    company: "Gucci",
    price: "$160",
    discount: false,
    size: "100ml",
    fragrance_type: "Oud",
    gender: "Unisex",
    image:
      "https://media.theperfumeshop.com/medias/sys_master/prd-images/hf2/hb1/9221923536926/prd-extra2-1179217_420x420/gucci-oud-intense-eau-de-parfum-420x420.jpg",
    origin_country: "Italy",
  },
  {
    id: 34,
    brand: "Tom Ford",
    name: "Oud Wood",
    company: "Tom Ford",
    price: "$230",
    discount_price: "$210",
    discount: true,
    size: "100ml",
    fragrance_type: "Oud",
    gender: "Unisex",
    image:
      "https://m.media-amazon.com/images/S/aplus-media/sota/9d4ce8f8-9467-4a9f-a212-cb66123b3391.__CR0,0,970,600_PT0_SX970_V1___.jpg",
    origin_country: "USA",
  },
  {
    id: 35,
    brand: "Yves Saint Laurent",
    name: "L'Homme",
    company: "Yves Saint Laurent",
    price: "$135",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://fragrancebd.com/wp-content/uploads/2020/02/YSL-Lhomme-EDT-100mL.jpg",
    origin_country: "France",
  },
  {
    id: 36,
    brand: "Versace",
    name: "Oud Noir",
    company: "Versace",
    price: "$140",
    discount_price: "$125",
    discount: true,
    size: "100ml",
    fragrance_type: "Oud",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXSmLyyeww99O8NiMqBcz5iPmcTklZVii7aw&s",
    origin_country: "Italy",
  },
  {
    id: 37,
    brand: "Burberry",
    name: "London",
    company: "Burberry",
    price: "$115",
    discount: false,
    size: "100ml",
    fragrance_type: "Spicy",
    gender: "Male",
    image:
      "https://m.media-amazon.com/images/I/71Cb1pnM5xL._AC_UF1000,1000_QL80_.jpg",
    origin_country: "UK",
  },
  {
    id: 38,
    brand: "Armani",
    name: "Emporio Armani",
    company: "Giorgio Armani",
    price: "$135",
    discount_price: "$120",
    discount: true,
    size: "100ml",
    fragrance_type: "Oriental",
    gender: "Male",
    image:
      "https://fragrancebd.com/wp-content/uploads/2024/03/Emporio-Armani-Lui-EDT-100mL.jpg",
    origin_country: "Italy",
  },
  {
    id: 39,
    brand: "Prada",
    name: "Prada Amber",
    company: "Prada",
    price: "$145",
    discount: false,
    size: "100ml",
    fragrance_type: "Amber",
    gender: "Unisex",
    image:
      "https://decantworldbd.com/wp-content/uploads/2022/12/314QEFgV42L.jpg",
    origin_country: "Italy",
  },
  {
    id: 40,
    brand: "Hermès",
    name: "Equipage",
    company: "Hermès",
    price: "$140",
    discount_price: "$125",
    discount: true,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3CJrpj__wtrrCSZ3uppqkzjh2Tt0AUCDkiQ&s",
    origin_country: "France",
  },
  {
    id: 41,
    brand: "Chanel",
    name: "Égoïste",
    company: "Chanel",
    price: "$155",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image: "https://m.media-amazon.com/images/I/51MCwslDJ5L._SL1024_.jpg",
    origin_country: "France",
  },
  {
    id: 42,
    brand: "Dior",
    name: "Dior Homme",
    company: "Christian Dior",
    price: "$145",
    discount_price: "$130",
    discount: true,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://buyperfumeinbangladesh.com/wp-content/uploads/2018/12/Dior-Homme-Intense-EDP-100ml-Bottle.webp",
    origin_country: "France",
  },
  {
    id: 43,
    brand: "Gucci",
    name: "Gucci Intense Oud",
    company: "Gucci",
    price: "$165",
    discount: false,
    size: "100ml",
    fragrance_type: "Oud",
    gender: "Unisex",
    image:
      "https://theperfumebox.com/cdn/shop/products/wgw4_300x.jpg?v=1643915642",
    origin_country: "Italy",
  },
  {
    id: 44,
    brand: "Tom Ford",
    name: "Noir Extreme",
    company: "Tom Ford",
    price: "$180",
    discount_price: "$165",
    discount: true,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5CtK73MppaUithVXZixx9ucS_r2EgzKD7Ig&s",
    origin_country: "USA",
  },
  {
    id: 45,
    brand: "Yves Saint Laurent",
    name: "La Nuit de L'Homme",
    company: "Yves Saint Laurent",
    price: "$135",
    discount: false,
    size: "100ml",
    fragrance_type: "Spicy",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsVdK2XDffs1tX203S1vWy1tPFTSNiBn673g&s",
    origin_country: "France",
  },
  {
    id: 46,
    brand: "Versace",
    name: "Pour Homme",
    company: "Versace",
    price: "$125",
    discount_price: "$110",
    discount: true,
    size: "100ml",
    fragrance_type: "Aromatic",
    gender: "Male",
    image:
      "https://m.media-amazon.com/images/I/61KuGoC1t5L._AC_UF1000,1000_QL80_.jpg",
    origin_country: "Italy",
  },
  {
    id: 47,
    brand: "Burberry",
    name: "Touch",
    company: "Burberry",
    price: "$115",
    discount: false,
    size: "100ml",
    fragrance_type: "Woody",
    gender: "Male",
    image: "https://m.media-amazon.com/images/I/81e0DRVXSuL.jpg",
    origin_country: "UK",
  },
  {
    id: 48,
    brand: "Armani",
    name: "Attitude",
    company: "Giorgio Armani",
    price: "$135",
    discount: false,
    size: "100ml",
    fragrance_type: "Oriental",
    gender: "Male",
    image:
      "https://m.media-amazon.com/images/I/61LqKe3Mp1L._AC_UF1000,1000_QL80_.jpg",
    origin_country: "Italy",
  },
  {
    id: 49,
    brand: "Prada",
    name: "Prada L'Homme Intense",
    company: "Prada",
    price: "$150",
    discount_price: "$135",
    discount: true,
    size: "100ml",
    fragrance_type: "Leather",
    gender: "Male",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStMYXn3DHoQyJif_ZTd_iKukQ6SGqKv87vtQ&s",
    origin_country: "Italy",
  },
  {
    id: 50,
    brand: "Hermès",
    name: "H24",
    company: "Hermès",
    price: "$140",
    discount: false,
    size: "100ml",
    fragrance_type: "Aromatic",
    gender: "Male",
    image:
      "https://cdn.riah.ae/storage/upload/images/2023/08/08/64d297f3ea6ee.jpg",
    origin_country: "France",
  },
];

export default alldata;
